---
- name: Make sure conflicting ODBC packages are removed
  yum:
    name:
      - unixODBC-utf16
      - unixODBC-utf16-devel
    state: absent

- name: Install mssql-server repo (CentOS, RedHat)
  get_url:
    url: https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/prod.repo
    dest: /etc/yum.repos.d/mssql-release.repo
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: Install mssql-server package
  yum:
    name: msodbcsql17 
    state: latest
  environment:
    ACCEPT_EULA: y

#- name: Install mssql-tools package
#  yum:
#    name: mssql-tools
#    state: latest
#  environment:
#    ACCEPT_EULA: 'y'

#OPTIONAL FOR DEVEL
#echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
#source ~/.bashrc
## optional: for unixODBC development headers
#sudo yum install -y unixODBC-devel
